/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LabRouteImport } from './routes/lab'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabRoiCalculationGuideRouteImport } from './routes/lab.roi-calculation-guide'
import { Route as LabB2bSaasCroGuideRouteImport } from './routes/lab.b2b-saas-cro-guide'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoiCalculationGuideRoute = LabRoiCalculationGuideRouteImport.update({
  id: '/roi-calculation-guide',
  path: '/roi-calculation-guide',
